language: rust
cache: cargo
rust:
    - stable
    - beta
    - nightly
os:
    - windows
    - linux
    - osx

before_script:
    - |
      (travis_wait rustup component add rustfmt-preview || true) &&
      (travis_wait rustup component add clippy-preview || true) &&
      (travis_wait rustup component add miri-preview || true)

script:
    - |
      ./ci-check.sh
