on:
  pull_request:
  push:
    branches:
      - master
  # Run once a week to preserve the cache
  # (even though it still feels the cache gets lost sometimes?)
  schedule:
    - cron: '0 0 * * 0'

name: benchmark pull requests

jobs:
  runBenchmark:
    name: run benchmark
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          default: true
          profile: minimal

      - name: Restore compile cache
        uses: Swatinem/rust-cache@v1

      - name: Restore previous benchmark data
        uses: actions/cache@v2
        with:
          path: ./bench-cache
          key: ${{ runner.os }}-benchmark

      - name: Run benchmarks
        # We choose just the tracking ones. There's a whole fleet that we check
        # that compile, but they are too heavy both to run in CI and to show in
        # the PRs. And they mostly compare us to other methods.
        #
        # Provide the bencher output, as the following tool knows how to read that.
        run: cargo bench | tee benches.out

      - name: Compare benchmarks
        uses: rhysd/github-action-benchmark@4eed2c2f4cd0d374720c4b913f79faa8aafcfa6b
        with:
          name: Track benchmarks
          tool: cargo
          output-file-path: benches.out
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: false
          alert-threshold: '150%'
          comment-on-alert: true
          comment-always: true
          fail-on-alert: true
          external-data-json-path: ./bench-cache/benchmark-data.json
          # Because it doesn't put it into the PR, it puts it into the commit :-|
          alert-comment-cc-users: '@vorner'
